# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    LightStatus = apps.get_model("api", "LightStatus")
    db_alias = schema_editor.connection.alias
    LightStatus.objects.using(db_alias).bulk_create([
        LightStatus(),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Country = apps.get_model("api", "LightStatus")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_light_on', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
