export AC_LOCATION={{ AC_LOCATION }}
export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
export SLACK_URL={{ SLACK_URL }}
export SLACK_TOKEN={{ SLACK_TOKEN }}
export HOSTNAME={{ ansible_hostname }}
